language: ruby
cache: bundler
env: CI=true
before_install: gem update bundler
script: make test
deploy:
  provider: s3
  bucket: brother.ly
  acl: public_read
  local_dir: "./build"
  skip_cleanup: true
  endpoint: psychedeli.ca.s3-website-us-east-1.amazonaws.com
  detect_encoding: true
  access_key_id:
    secure: ClGk2sYEjCWOy2fINesXH90UI3hN2fuddCJZ3asuo4M2dTx5vXkBk5pIri+UL5shUYhaiDTPnFPE3y2xN9YPymHKK5NSAbHNe7YsnzM4/9e0bhES1LZk05Ui+y6HAVhprTvOHdVb5/WmahZ/H9XNYd4SUeh46gdB7VGyGlj7uoo=
  secret_access_key:
    secure: LDgNdFtJtcZG0J7MDwPHju5KV5/AB8qj0PSadae4fCaqXiErQg/v83Cp1Lsq6rAgZ+qkTFUnYERSDQN3oyXmlWxnSGQWf72YjUR9JNGCXe7LIjUKUhWXtTjUfjolJR/BuTeuPspiKXdx0goDIYYFNENZOWkRmPPxYBvb+nKTPWE=
